abbr i3conf "nvim ~/.config/i3/config"
abbr fishconf "nvim ~/.config/fish/config.fish"
abbr shortcutconf "nvim ~/.config/fish/shortcut.fish"
abbr nvimconf "nvim ~/.config/nvim/init.vim"
abbr alaconf "nvim ~/.config/alacritty/alacritty.yml"
